// @baumy/types: Zod schemas shared across boundaries (AGENTS.md "Validate with
// Zod at every boundary"). No I/O, no framework imports.

export { Surface, SURFACES } from "./surface";
export {
  AVATAR_SPRITES,
  AvatarSprite,
  DISPLAY_NAME_MAX,
  DisplayName,
  KioskPin,
  MEMBER_COLORS,
  MEMBER_COLOR_NAMES,
  MemberColor,
  MemberRole,
  TelegramLinkCode,
  TelegramUserId,
  TELEGRAM_ID_MESSAGE,
  memberColorName,
} from "./member";
export {
  AVATAR_NAME_MAX,
  AvatarId,
  AvatarName,
  AvatarRef,
  ChooseAvatar,
  JoinAvatarId,
  NewAvatar,
  AVATAR_HEIGHTS,
  AVATAR_POSES,
  DEFAULT_AVATAR_HEIGHT,
  PreviewAvatar,
  type AvatarImage,
  type AvatarPose,
  type AvatarSprites,
} from "./avatars";
export {
  KIOSK_DEVICE_NAME_MAX,
  KIOSK_PAIRING_CODE_LENGTH,
  KioskDeviceName,
  KioskPairingCode,
} from "./kiosk";
export {
  BASE_POINTS_MAX,
  BASE_POINTS_MIN,
  BasePoints,
  CHORE_ICONS,
  CHORE_KINDS,
  CHORE_NAME_MAX,
  COMPLETION_NOTE_MAX,
  COOLDOWN_HOURS_MAX,
  ChoreIcon,
  ChoreKind,
  ChoreName,
  CompletionNote,
  ConfirmMode,
  CooldownHours,
  DISPUTE_REASON_MAX,
  DisputeReason,
  EFFORT_FACTOR_MAX,
  EFFORT_FACTOR_MIN,
  EffortFactorPct,
  ProofMode,
  WEIGHT_CHANGE_REASON_MAX,
  WeightChangeReason,
  cooldownMinutesFromHours,
} from "./chore";
export {
  ADJUSTMENT_POINTS_MAX,
  ADJUSTMENT_REASON_MAX,
  AdjustmentPoints,
  AdjustmentReason,
  POT_AMOUNT_MAX_CENTS,
  POT_NOTE_MAX,
  PotAmountCents,
  PotMonth,
  PotNote,
  PrizeMode,
  potMonthDate,
} from "./scores";
export {
  CalendarDate,
  CalendarEventId,
  CalendarEventUpdate,
  CalendarTime,
  EVENT_DESCRIPTION_MAX,
  EVENT_LOCATION_MAX,
  EVENT_MAX_DAYS,
  EVENT_TITLE_MAX,
  EventKind,
  EventRange,
  LIST_EVENTS_MAX_DAYS,
  NewCalendarEvent,
  checkEventFields,
  daysBetween,
  eventFieldsShape,
  isCalendarDate,
} from "./calendar";
export {
  ListNotesInput,
  NOTE_BODY_MAX,
  NOTE_COLORS,
  NOTE_LIST_MAX,
  NOTE_TITLE_MAX,
  NewNote,
  NoteBody,
  NoteColor,
  NoteColorChoice,
  NoteFlag,
  NoteId,
  NotePin,
  NoteRef,
  NoteTitle,
  NoteUpdate,
} from "./notes";
export {
  ListShoppingInput,
  SHOPPING_ITEMS_MAX,
  SHOPPING_ITEM_MAX,
  ShoppingItem,
  ShoppingItems,
  ShoppingWrite,
  splitShoppingText,
} from "./shopping";
export {
  ListRemindersInput,
  NewReminder,
  REMINDER_BODY_MAX,
  REMINDER_TITLE_MAX,
  ReminderBody,
  ReminderId,
  ReminderRef,
  ReminderTitle,
} from "./reminders";
export {
  LOGIN_CODE_MAX,
  LOGIN_CODE_MIN,
  LoginApprovalStart,
  LoginCode,
  LoginRequestId,
} from "./login";
